#ifndef LRUCACHE_H
#define	LRUCACHE_H

#include "BaseCache.h"

class LRUCache : public BaseCache
{
    public:
        /* Stores prefetch lines which are evicted from cache 
         * without getting demand access in <LINE,PC> format
         */
        std::unordered_map<unsigned int, unsigned int> early_prefetch;
        /* Stores total misses faced by a PC 
         * and number of early prefetch
         */
        std::unordered_map<unsigned int,stat_t*> demand_miss_map;
        /* Stores total prefetch generated by a PC
         * and number of early prefetch among them.
         */
        std::unordered_map<unsigned int, stat_t*> pc_prefetch_map;
        
    public:
        LRUCache(char*,unsigned int,unsigned int,unsigned int);
        ~LRUCache();
        
        /*Base class functions */
        int find(unsigned int,unsigned int);
        int find(unsigned int);
        void promotion(unsigned int,unsigned int, bool);
        unsigned int victimize(unsigned int);
        void eviction(unsigned int,unsigned int);
        void insertion(unsigned int,unsigned int,unsigned int,unsigned int, bool);
        int update(unsigned int, unsigned int, bool);
        void heart_beat_stats(int);
        void final_stats(int);

        /* Own functions */
        void update_early_prefetch_map(unsigned int, unsigned int);
        void update_pc_prefetch_map(unsigned int);

};

#endif	/* LRUCACHE_H */



